server:
    port: 9102
spring:
    application:
        name: microservice-gateway
    cloud:
        config:
            import-check:
                enabled: false
eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://localhost:9102/eureka/