server:
    port: 8083
spring:
    application:
        name: microservice-eureka
    cloud:
        config:
            import-check:
                enabled: false
eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://localhost:8083/eureka/

