server:
    port: 8083
spring:
    application:
        name: microservice-eureka
eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://localhost:8083/eureka/
    instance:
        hostname: localhost
