spring:
    application:
        name: microservice-gateway
    cloud:
        config:
            import-check:
                enabled: false
eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://eureka-server:8791/eureka/