spring:
  cloud:
    gateway:
    discovery:
      locator:
        enabled: true
    routes:
      - id: patients
        uri: lb://patients-service
        predicates:
        - Path=/patients/**
server:
  port: 9103
eureka:
  client:
    serviceURL:
      defaultZone: http://glycoguard-eureka:9102/eureka
logging:
  level:
    org:
      springframework:
        security: TRACE