server:
  port: 9004
spring:
  cloud:
    gateway:
      routes:
        - id: patients-service
          uri: lb://patients-service
          predicates:
            - Path=/patients/**
        - id: notes-service
          uri: lb://notes-service
          predicates:
            - Path=/notes/**
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/