spring:
  datasource:
    url: jdbc:mysql://localhost:3306/glycoguard
    username: root
    password: .Logme1nn
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    serialization:
      fail-on-empty-beans: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 9111
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
management:
  endpoints:
    web:
      exposure:
        include: refresh
logging:
  level:
    org.springframework.security: DEBUG
customizer:
  maxPatients: 2