spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: glycoguard
      auto-index-creation: true
server:
  port: 9112
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://glycoguard-eureka:9102/eureka/
management:
  endpoints:
    web:
      exposure:
        include: refresh
logging:
  level:
    org.springframework.security: DEBUG